# what are the actual correlations between decathlon events? how does it compare to the posterior predictive distributions generated by the compositional and simple models? date: aug 14, 2025
set.seed(2)
library(tidyverse)
library(readxl)
library(rstan)
library(rlist)
library(tidyselect)
library(patchwork)
library(forcats)
library(mvtnorm)
library(knitr)

setwd("~/school/wisconsin/research_repo/decathlon")
study = "new_stan_sim"
data_dir = "new_stan_sim/data/"
script_dir = "new_stan_sim/study/"
stan_dir = "new_stan_sim/stan_mods/"

source(paste0(script_dir, "decathlon_funs.R"))
# source(paste0(script_dir, "settings_gen_data.R"))


# actual correlations
online_data_filter <- read_csv(paste0(data_dir,"online_data_filter.csv")) %>%
  filter(year(dob) > 1950,
         discus > 2) %>%
  group_by(name, dob) %>%
  mutate(athlete_id = cur_group_id()) %>%
  unique()
event_sums <- get_event_sums_df(online_data_filter)
dec_events <- c("hundred_m", "long_jump", "shot_put",
                "high_jump", "four_hundred_m", "hurdles",
                "discus", "pole_vault", "javelin",
                "fifteen_hundred_m")

cor_df <- expand.grid(event1 = dec_events, event2 = dec_events) %>%
  mutate(emp_cor = NA)
for (i in 1:nrow(cor_df)){
  event1 <- as.character(cor_df$event1[i])
  event2 <- as.character(cor_df$event2[i])
  cor_df$emp_cor[i] <- cor(online_data_filter[event1], online_data_filter[event2])
}
  

# correlations from posterior predictives.
sim_comp <- readRDS(file = "results/comp_sim_for_all_athletes.RData")
comp_events <- sim_comp$sim_events
sim_simple <- readRDS(file = "results/simple_sim_for_all_athletes.RData")
simple_events <- sim_simple$sim_events

comp_events <- comp_events %>%
  mutate(it_number = (((index) - 1) %/% 8668) + 1)
simple_events <- simple_events %>%
  mutate(it_number = (((index) - 1 ) %/% 8668) + 1)

# make seperate dataframe for each iteration before calculating correlation
comp_events_list <- vector("list", 2000)
simple_events_list <- vector("list", 2000)
for (i in 1:length(comp_events_list)) {
  comp_events_list[[i]] <- comp_events %>%
    filter(it_number == i)
  simple_events_list[[i]] <- simple_events %>%
    filter(it_number == i)
}

cor_df_sim <- expand.grid(event1 = dec_events, event2 = dec_events,
                      it_number = 1:2000, comp = c("comp", "simple"))
for (i in 1:nrow(cor_df_sim)) {
  if (i %% 2000 == 0){ print(i)}
  it_number = cor_df_sim$it_number[i]
  event1 = as.character(cor_df_sim$event1[i])
  event2 = as.character(cor_df_sim$event2[i])
  comp = cor_df_sim$comp[i]
  if (cor_df_sim$comp[i] == "comp") {
    df = comp_events_list[[it_number]]
  } else{
    df = simple_events_list[[it_number]]
  }
  cor_df_sim$sim_cor[i] <- cor(df[event1], df[event2])
}

cor_df_sim <- cor_df_sim %>%
  mutate(comp = case_when(comp == "comp" ~ "Compositional",
                          .default = "Simple"))

cor_box2 <- ggplot(data = cor_df_sim %>%
         filter(event1 == "javelin",
                event2 == "long_jump"),
       mapping = aes(x = sim_cor, fill = comp,
                     color = comp)) + 
  geom_boxplot(alpha = .2) +
  geom_vline(xintercept = cor_df %>%
               filter(event1 == "javelin",
                      event2 == "long_jump") %>%
               pull(emp_cor),
             color = "tomato") + theme_bw() +
  labs(title = "JV x LJ correlation",
       x = "Simulated correlation strength",
       fill = "Model",
       color = "Model") + 
  scale_color_brewer(type = "qual",
                     palette = 2) +
  scale_fill_brewer(type = "qual",
                    palette = 2) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) 

cor_box1 <- ggplot(data = cor_df_sim %>%
         filter(event1 == "hundred_m",
                event2 == "long_jump"),
       mapping = aes(x = sim_cor, fill = comp,
                     color = comp)) + 
  geom_boxplot(alpha = .2) +
  geom_vline(xintercept = cor_df %>%
               filter(event1 == "hundred_m",
                      event2 == "long_jump") %>%
               pull(emp_cor),
             color = "tomato") + theme_bw() +
  labs(title = "LJ x 100m correlation",
       x = "Simulated correlation strength",
       fill = "Model",
       color = "Model") + 
  scale_color_brewer(type = "qual",
                     palette = 2) +
  scale_fill_brewer(type = "qual",
                    palette = 2)  +
  theme(axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())


cor_box1 / cor_box2
ggsave("writing/decathlon_manu/figures/correlation_plots.png", width = 7, height = 5,
       units = "in")




cor_table <- data.frame(matrix(nrow = 10, ncol = 11))
colnames(cor_table) <- c("event", dec_events)
cor_table["event"] <- dec_events
for (i in 1:10) {
  for (j in i:10) {
    event1_name <- colnames(cor_table)[i + 1]
    event2_name <- cor_table$event[j]
    cor <- cor_df %>%
      filter(event1 == event1_name,
             event2 == event2_name) %>%
      pull(emp_cor)
    cor_table[i,j+1] <- cor
  }
}
colnames(cor_table) <- c("Event", "100m", "LJ", "SP", "HJ", "400m", "110mH", "DT", "PV", "JT", "1500m")
cor_table$Event <- c("100m", "LJ", "SP", "HJ", "400m", "110mH", "DT", "PV", "JT", "1500m")

cor_table %>%
  kable(caption = "Emperical correlations between decathlon events in observed data, rounded to 2 digits.",
        escape = F,
        label = "emp_cor",
        digits = 2,
        format = "latex",
        booktabs = T)

quantile_df_simple <- cor_df_sim %>%
  filter(comp == "Simple") %>%
  group_by(event1, event2, comp) %>%
  summarize(q2.5 = quantile(sim_cor, 0.025),
            q97.5 = quantile(sim_cor, 0.975))


cor_table_simple <- data.frame(matrix(nrow = 10, ncol = 11))
colnames(cor_table_simple) <- c("event", dec_events)
cor_table_simple["event"] <- dec_events
for (i in 1:10) {
  for (j in i:10) {
    event1_name <- colnames(cor_table_simple)[i + 1]
    event2_name <- cor_table_simple$event[j]
    cor2.5 <- quantile_df_simple %>%
      filter(event1 == event1_name,
             event2 == event2_name) %>%
      pull(q2.5) %>%
      round(digits = 2)
    cor97.5 <- quantile_df_simple %>%
      filter(event1 == event1_name,
             event2 == event2_name) %>%
      pull(q97.5) %>%
      round(digits = 2)
    cor_table_simple[i,j+1] <- paste0(cor2.5, ", ", cor97.5, 
                               sep = "")
  }
}
colnames(cor_table_simple) <- c("Event", "100m", "LJ", "SP", "HJ", "400m", "110mH", "DT", "PV", "JT", "1500m")
cor_table_simple$Event <- c("100m", "LJ", "SP", "HJ", "400m", "110mH", "DT", "PV", "JT", "1500m")
cor_table_simple <- cor_table_simple[,-2]
cor_table_simple %>%
  kable(caption = "2.5% and 97.5% quantiles for posterior predictive correlation between decathlon events from 2000 simulated datasets from the simple model, rounded to 2 digits.",
        escape = F,
        label = "sim_cor_simple",
        digits = 2,
        format = "latex",
        booktabs = T)



quantile_df_comp <- cor_df_sim %>%
  filter(comp == "Compositional") %>%
  group_by(event1, event2, comp) %>%
  summarize(q2.5 = quantile(sim_cor, 0.025),
            q97.5 = quantile(sim_cor, 0.975))


cor_table_comp <- data.frame(matrix(nrow = 10, ncol = 11))
colnames(cor_table_comp) <- c("event", dec_events)
cor_table_comp["event"] <- dec_events
for (i in 1:10) {
  for (j in i:10) {
    event1_name <- colnames(cor_table_comp)[i + 1]
    event2_name <- cor_table_comp$event[j]
    cor2.5 <- quantile_df_comp %>%
      filter(event1 == event1_name,
             event2 == event2_name) %>%
      pull(q2.5) %>%
      round(digits = 2)
    cor97.5 <- quantile_df_comp %>%
      filter(event1 == event1_name,
             event2 == event2_name) %>%
      pull(q97.5) %>%
      round(digits = 2)
    cor_table_comp[i,j+1] <- paste0(cor2.5, ", ", cor97.5, 
                                    sep = "")
  }
}
colnames(cor_table_comp) <- c("Event", "100m", "LJ", "SP", "HJ", "400m", "110mH", "DT", "PV", "JT", "1500m")
cor_table_comp$Event <- c("100m", "LJ", "SP", "HJ", "400m", "110mH", "DT", "PV", "JT", "1500m")
cor_table_comp <- cor_table_comp[,-2]
cor_table_comp %>%
  kable(caption = "2.5% and 97.5% quantiles for posterior predictive correlation between decathlon events from 2000 simulated datasets from the compositional model, rounded to 2 digits.",
        escape = F,
        label = "sim_cor_comp",
        digits = 2,
        format = "latex",
        booktabs = T)
